config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, controllers: {
    sessions: 'admins/sessions',
  }
  devise_for :users, controllers: {
    registrations: 'users/registrations',
  }
  resources :users, only: [:show]
  resources :hanabis

  root               to: 'static_pages#home'
  get :about,        to: 'static_pages#about'
  get :terms,        to: 'static_pages#terms'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/hanabi.rb
class Hanabi < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :title, presence: true, length: { maximum: 30 }
  validates :address, presence: true, length: { maximum: 50 }
  validates :body, presence: true, length: { maximum: 140 }
  attachment :image
end

app/controllers/hanabis_controller.rb
class HanabisController < ApplicationController
  before_action :user_signed_in?
  before_action :authenticate_user!
  before_action :correct_user, only: %i(edit update)

  def index
    @user = current_user
    @hanabis = Hanabi.all
  end

  def show
    @hanabi = Hanabi.find(params[:id])
  end

  def new
    @user = current_user
    @hanabi = Hanabi.new
  end

  def create
    @hanabi = Hanabi.new(hanabi_params)
    @hanabi.user_id = current_user.id
    if @hanabi.save
      flash[:notice] = '花火スポットを登録しました'
      redirect_to hanabi_path(@hanabi)
    else
      render 'new'
    end
  end

  def edit
    @hanabi = Hanabi.find(params[:id])
  end

  def update
    @hanabi = Hanabi.find(params[:id])
    if @hanabi.update(hanabi_params)
      flash[:notice] = '花火スポット情報を更新しました'
      redirect_to @hanabi
    else
      render 'edit'
    end
  end

  def destroy
    @hanabi = Hanabi.find(params[:id])
    @hanabi.destroy
    flash[:notice] = '削除しました'
    redirect_to :hanabis
  end

  private

  def hanabi_params
    params.require(:hanabi).permit(:title, :body, :address, :image)
  end

  def correct_user
    @hanabi = Hanabi.find(params[:id])
    @user = @hanabi.user
    redirect_to(hanabis_path) unless @user == current_user
  end
end

app/helpers/hanabis_helper.rb
module HanabisHelper
end

app/views/hanabis/_hanabi_form.html.erb
<%= form_with model: @hanabi, local: true do |f| %>
  <div class = 'form-group'>
    <%= f.label :title %>　<span class="input-need">※必須</span>
    <%= f.text_field :title, class: 'form-control', id: 'hanabi_title' %>
  </div>
  <div class = 'form-group'>
    <%= f.label :address %>
    <%= f.text_field :address, class: 'form-control', id: 'address' %>
  </div>
  <div class = 'form-group'>
    <%= f.label :body %>
    <%= f.text_field :body, class: 'form-control', id: 'explanation' %>
  </div>
  <div class = 'form-group'>
    <%= f.attachment_field :image %> 
  </div>
  <%= f.submit nil, class: 'btn btn-primary' %>
<% end %>

app/views/hanabis/edit.html.erb
<% provide(:title, "花火スポットの編集") %>
<div class="container">
  <%= render 'shared/error' , obj:@hanabi%>
  <div class="row">
    <div class="col-md-6 col-md-offset-3">
      <%= form_with model: @hanabi, local: true do |f| %>
        <div class = 'form-group'>
          <%= f.label :タイトル %>　<span class="input-need">※必須</span>
          <%= f.text_field :title, class: 'form-control', id: 'hanabi_title' %>
        </div>
        <div class = 'form-group'>
          <%= f.label :住所 %>
          <%= f.text_field :address, class: 'form-control', id: 'address'  %>
        </div>
        <div class = 'form-group'>
          <%= f.label :説明 %>
          <%= f.text_field :body, class: 'form-control', id: 'explanation'  %>
        </div>
        <div class = 'form-group'>
          <%= f.attachment_field :image %> 
        </div>
        <%= f.submit "更新する", class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
</div>

app/views/hanabis/index.html.erb
<div class = "container-fluid">
  <div class = "hanabi-posts m-4">
    <h1 class = "pb-2">あなたが登録したスポット一覧</h1>
      <table class = "hanabi-table border-top mx-3">
        <thead>
          <tr class = "border-bottom">
            <th class = "col-3 text-center py-2">画像</th>
            <th class = "col-2 text-center py-2">タイトル</th>
            <th class = "col-3 text-center py-2">住所</th>
            <th class = "col-2 text-center py-2">説明</th>
            <th class = "col-2 text-center py-2">作成日</th>
          </tr>
        </thead>
        <tbody>
          <% @hanabis.each do |hanabi| %>
            <% if hanabi.user_id == current_user.id %>  
              <tr class = "border-bottom  py-2">
                <div>
                  <td class = "p-2 text-center">
                    <%= link_to hanabi_path(hanabi) do %>
                      <%= attachment_image_tag hanabi,:image, class:"hanabi-img-reg" %>
                    <% end %>
                  </td>
                  <td class = "px-2 text-center"><%= link_to hanabi.title , hanabi_path(hanabi) %></td>
                  <td class = "px-2 text-wrap"><%= hanabi.address %></td>
                  <td class = "px-2 text-center">¥<%= hanabi.body %>-</td>
                  <td class = "px-2 text-center"><%= hanabi.updated_at.strftime("%Y年%m月%d日") %></td>
                </div>
              </tr>
            <% end %>
          <% end %>
        </tbody>  
      </table>
  </div>
</div>

app/views/hanabis/new.html.erb
<% provide(:title, "花火スポット登録") %>
<div class="container">
  <h1>花火スポット登録</h1>
  <%= render 'shared/error' , obj:@hanabi%>
  <div class="row">
    <div class="col-sm-5 mx-auto mt-5">
      <%= render 'hanabis/hanabi_form' %>
    </div>
  </div>
</div>

app/views/hanabis/show.html.erb
<% provide(:title, "#{@hanabi.title}") %>
<div class="container">
  <div class="row">
    <h2 class="hanabi-name"><%= @hanabi.title %></h2>
    <h2 class="hanabi-name"><%= @hanabi.address %></h2>
    <h4><%= @hanabi.body %></h4>
    <%= attachment_image_tag @hanabi, :image %>
    <h4 class="hanabi-reference">説明：<%= link_to "#{@hanabi.body}", @hanabi.body, target: "_blank" %></h4>
  </div>
  <div class="change-hanabi">
    <% if current_user == @hanabi.user %>
      <%= link_to "編集", edit_hanabi_path(@hanabi), class: 'edit-hanabi' %>　
      <%= button_to "削除", hanabi_path(@hanabi), method: :delete, data: { confirm: "本当に削除しますか?" }, class: 'destroy-hanabi' %>
    <% end %>
  </div>
</div>